README.md

Fix helm charts link

---

README.md

typo fixed. port 300 to 3000.
#169 

typo fixed port 300 to 3000

---

.github/scripts/get_release_version.py
.github/workflows/dapr_cli.yaml

Switch Azure Pipelines to GitHub Actions
#180

Switch Azure Pipelines to GitHub Actions

---

.github/workflows/dapr_cli.yaml

Fix dpar_cli to dapr_cli
#180 

Fix dpar_cli to dapr_cli

---

README.md

[CI] Update build badge

---

README.md

Update doc for change in https://github.com/dapr/cli/pull/184

Update README for uninstall

---

pkg/standalone/run.go

fix non-existing component dir error

---

cmd/init.go

remove redis on local init (#206)

---

README.md
cmd/dapr.go
cmd/invoke.go
cmd/list.go
cmd/run.go
cmd/stop.go
cmd/uninstall.go
docs/development/development.md
docs/reference/dapr-init.md
docs/reference/dapr-run.md
docs/reference/reference.md
install/install.ps1
install/install.sh
pkg/standalone/run.go
pkg/standalone/standalone.go
vendor/github.com/dapr/dapr/pkg/apis/components/v1alpha1/types.go
vendor/github.com/dapr/dapr/pkg/components/standalone_loader.go
vendor/github.com/docker/docker/client/client.go

Capitalized Dapr name throughout

Capitalized Dapr and uppercase CLI

---

cmd/publish.go
pkg/api/api.go
pkg/invoke/invoke.go
pkg/kubernetes/client.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/list.go
pkg/kubernetes/run.go
pkg/kubernetes/uninstall.go
pkg/print/print.go
pkg/publish/publish.go
pkg/standalone/list.go
pkg/standalone/run.go
pkg/standalone/standalone.go
pkg/standalone/stop.go
pkg/version/version.go

Cleans up a few comments and strings throughout.

Clean up a few comments and strings

---

.gitignore

Added filter for Visual Studio .vs folder.

Added filter for Visual Studio

---

pkg/standalone/standalone.go

download only release build
#258

download only release build

---

pkg/standalone/standalone.go

Make linter happy

---

install/install.ps1

Update powershell script message from standalone to selfhosted
N/A

Update powershell script message from standalone to selfhosted

---

cmd/init.go
go.sum
pkg/kubernetes/client.go

add gcp auth

---

README.md
cmd/init.go
go.sum
pkg/kubernetes/client.go

hotfix to release-0.4

---

pkg/rundata/rundata.go
pkg/standalone/uninstall.go

Delete rundata file on dapr uninstall
Related to #273 but does not completely fix.  See thread.

Delete rundata file on uninstall

---

pkg/kubernetes/list.go
pkg/kubernetes/logs.go
pkg/standalone/run.go
pkg/standalone/run_test.go

Replaced dapr-id with app-id for consistency
Please reference the issue this PR will close: [#_[284]_](https://github.com/dapr/cli/issues/284)

Replace DaprID with AppID

---

install/install.ps1
install/install.sh

Modified cli install script to get release version (not rc version)
Please reference the issue this PR will close: [#_[263]_](https://github.com/dapr/cli/issues/263)

Modify install script to download release version

---

pkg/standalone/run.go

Fixing bug where cannot run 2 sidecars in standalone via cli.
Please reference the issue this PR will close: #275 

Fixing bug where cannot run 2 sidecars in standalone via cli.

---

install/install.sh

* Fixes bug that downloads rc version
Fixed the bug that's downloading rc version

Fix one line installer bug

---

cmd/run.go
pkg/standalone/list.go

Fix 'dapr list' to include cli PID and info
Please reference the issue this PR will close: #296 

[Hotfix 0.5] Fix 'dapr list' to include cli PID and info

---

cmd/run.go
pkg/standalone/list.go

Fix 'dapr list' to include cli PID and info
Please reference the issue this PR will close: #296 

[Master] Fix 'dapr list' to include cli PID and info

---

pkg/kubernetes/kubernetes.go
pkg/kubernetes/uninstall.go
pkg/standalone/standalone.go
pkg/version/version.go

Updated the URL to pull dapr-operator.yaml
Please reference the issue this PR will close: [#_[292]_](https://github.com/dapr/cli/issues/292)

Update the URL to pull dapr-operator.yaml

---

Makefile

This reverts commit 65fee35c461dc8c377c52cfce25fbd6f8d9966de.
Tar file for homebrew is specialized. It is more complex than simply a file name. That automation will be part of 0.7. I am creating the homebrew bottle manually on my desktop now.
Please reference the issue this PR will close: #171 

Revert "Adds tar.gz for Homebrew. (#304)"

---

docs/development/development.md

Add `go` version and `golangci-lint` requirement
Issue #310

Update pre-requisites for dapr cli development

---

install/install.ps1

Add install path as a parameter

---

cmd/run.go
docs/reference/dapr-run.md
pkg/standalone/run.go
pkg/standalone/run_test.go

Revert usage of enableJSONSecretStore flag.

---

pkg/standalone/standalone.go

Components rc fix

---

cmd/run.go

Fix components path help message.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1619

Fix components path help message.

---

cmd/run.go
pkg/standalone/common.go
pkg/standalone/run.go
pkg/standalone/run_test.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go

Fixes https://github.com/dapr/cli/issues/366

passing components folder to daprd

---

cmd/run.go
pkg/standalone/common.go
pkg/standalone/run.go
pkg/standalone/run_test.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go

fixes #366 
This is for release-0.8 branch

passing components folder to daprd (#367)

---

pkg/standalone/standalone.go

Merge back to master
**NOTE: DO NOT SQUASH-MERGE!**
n/a

Merge back to master

---

CONTRIBUTING.md
docs/reference/dapr-components.md
docs/reference/dapr-configurations.md
docs/reference/dapr-init.md
docs/reference/dapr-invokeGet.md
docs/reference/dapr-invokePost.md
docs/reference/dapr-list.md
docs/reference/dapr-logs.md
docs/reference/dapr-mtls.md
docs/reference/dapr-publish.md
docs/reference/dapr-run.md
docs/reference/dapr-status.md
docs/reference/dapr-stop.md
docs/reference/reference.md

This PR is for #375.
Updated the Dapr CLI references and the contribution guideline in order to keep them up-to-date.
Please reference the issue this PR will close: #375 
This PR doesn't include any code change, so I didn't create/update new tests for this PR.

Update CLI Reference and Contribution Guidelines

---

README.md
pkg/standalone/standalone.go
pkg/standalone/uninstall.go

Remove `fmt.Println` messages. With multiple goroutines since not each goroutine has handle to spinner, print out what has been done as a result of running `init`, `uninstall --all` or `init --slim`
```bash
$ ./dist/darwin_amd64/release/dapr init 
⌛  Making the jump to hyperspace...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /usr/local/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
$ ./dist/darwin_amd64/release/dapr uninstall --all 
ℹ️  Removing Dapr from your machine...
ℹ️  Removing binary: /usr/local/bin/daprd
ℹ️ …
```

Fix messages on init and uninstall

---

pkg/kubernetes/configuration.go

Fix operator pod crash

---

README.md

Add readme note for linux. 
Please reference the issue this PR will close: #380 

add readme note for uninstall in linux

---

README.md
cmd/dapr.go
cmd/init.go
cmd/uninstall.go
docs/reference/dapr-init.md
docs/reference/dapr-uninstall.md
pkg/standalone/common.go
pkg/standalone/run.go
pkg/standalone/run_test.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go
pkg/standalone/version.go
pkg/version/version.go

Fixes https://github.com/dapr/cli/issues/411

Change init and uninstall behavior for self hosted mode

---

README.md
cmd/init.go
cmd/uninstall.go

Make version flags consistent for init/uninstall

---

README.md
cmd/run.go
docs/reference/dapr-run.md

Normalized "dapr run" flags
Please reference the issue this PR will close: #416 

Normalize "dapr run" flags

---

cmd/publish.go
pkg/publish/publish.go

Add pubsub component name to publish command

---

README.md

Update readme for multi pubsub - refs to dapr publish need updates.

Update readme for multi pubsub

---

pkg/kubernetes/client.go

Fixing flag parsing only when required.
Please reference the issue this PR will close: #439 

Parse flags when needed in getConfig

---

pkg/kubernetes/client.go

Need to merge release-0.10 branch to master as part of release process

Merge release-0.10 branch to master as part of release process

---

.github/workflows/dapr_cli.yaml
docs/development/development.md
go.mod
go.sum

Upgrade go lang version to 1.15
Please reference the issue this PR will close: #442 

Upgrade go lang ver to 1.15

---

cmd/run.go

Do not print Success status on an error.
Please reference the issue this PR will close: #348 

Fix logs on error

---

pkg/kubernetes/status.go

Fix wrong status when ha mode is enabled

---

pkg/publish/publish.go

Fixed publish command bug when dashboard is up
Please reference the issue this PR will close: #458 

Fix publish command bug when dashboard is up

---

.codecov.yaml
.github/workflows/dapr_cli.yaml
Makefile
README.md

Add CodeCov GitHub action & badge.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2069

Add CodeCov GitHub action & badge.

---

cmd/dashboard.go
pkg/standalone/dashboard.go
pkg/standalone/dashboard_test.go

Propagates dashboard port in standalone mode.
Please reference the issue this PR will close: #463 

Propagates dashboard port in standalone mode.

---

pkg/kubernetes/kubernetes.go

Move helm repo from ACR to GH Page
#467

Move helm repo from ACR to GH Page

---

.github/workflows/dapr_cli.yaml

Fixing github-release to 1.3.1.

Fixing github-release to 1.3.1.

---

.github/workflows/dapr_cli.yaml
Makefile

build arm64 binary in CI

---

cmd/status.go
pkg/kubernetes/pods.go
pkg/kubernetes/pods_test.go
pkg/kubernetes/status.go
pkg/kubernetes/status_test.go

Merge back changes from release-0.11 branch

Merge back changes from release-0.11 branch

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add RELEASE NOTE to issue and feature template.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2171

Add RELEASE NOTE to issue and feature template.

---

README.md
cmd/run.go
docs/reference/dapr-run.md
pkg/standalone/run.go
pkg/standalone/run_test.go

Add ssl command to dapr run

---

cmd/completion.go

Minor update to keep --help consistent with the other commands.
Please reference the issue this PR will close: NONE 

Adds 'Updates help message for completion.

---

pkg/standalone/publish.go

Allow any 2xx status code for CLI
Please reference the issue this PR will close: #510

All any 2xx status code for success on standalone publish (#510)

---

.github/ISSUE_TEMPLATE/proposal.md

Add release note to GH proposal template

Add release note to GH proposal template

---

install/README.md
install/install.ps1
install/install.sh

Support version params in one liner script
Please reference the issue this PR will close: #516 

Support version param in one liner script

---

cmd/completion.go
cmd/dashboard.go
cmd/invoke.go
cmd/publish.go
cmd/run.go
cmd/stop.go
pkg/standalone/client.go
pkg/standalone/invoke.go

Please reference the issue this PR will close: #530 
closes #531 
https://github.com/dapr/docs/issues/972

Make flags consistent across commands.

---

README.md
pkg/standalone/standalone.go

Move trace Zipkin address into Configuration's trace section.
I have a follow-up PR for unit testing, but it requires some additional refactoring that can be done separately.
Please reference the issue this PR will close: #534 

Move trace Zipkin address into Configuration's trace section

---

cmd/components.go
cmd/configurations.go
cmd/dashboard.go
cmd/init.go
cmd/invoke.go
cmd/list.go
cmd/logs.go
cmd/mtls.go
cmd/publish.go
cmd/run.go
cmd/status.go
cmd/stop.go
cmd/uninstall.go

Update help messages to mention platform and provide examples for all commands.
Please reference the issue this PR will close: #538 
close #539 

updated help messages. provide example for commands.

---

README.md
cmd/publish.go
pkg/standalone/client.go
pkg/standalone/publish.go
pkg/standalone/publish_test.go

Adds publish-app-id to publish command
Please reference the issue this PR will close: #536 

Adds publish-app-id to publish command

---

cmd/init.go
cmd/run.go

Add dotnet run example

---

cmd/run.go

Merge master branch into release-1.0. (Recut rc.3)

Merge master branch into release-1.0

---

.gitignore
cmd/run.go
pkg/standalone/run.go
pkg/standalone/run_test.go

add `--metrics-port` on run command
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/554

feat: add metrics_port flag

---

README.md
cmd/init.go
cmd/upgrade.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/upgrade.go
pkg/kubernetes/upgrade_test.go

Closes https://github.com/dapr/cli/issues/574

Add support for all helm values on init/upgrade

---

cmd/init.go

Fix wrong URL

---

cmd/components.go
pkg/kubernetes/components.go
pkg/kubernetes/components_test.go
pkg/kubernetes/configurations.go
utils/utils.go

Adds name filtering and output formatting for the components command.
@artursouza You might be the best person to review this since you did #549.
Resolves: #553

Name filtering and output format for the components command

---

.github/workflows/dapr_cli.yaml

Generate checksum files on release.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/626
Tested in here: https://github.com/artursouza/dapr/releases/tag/v0.3.13

Generate checksum files on release.

---

cmd/upgrade.go

Fixes https://github.com/dapr/cli/issues/592

Fix upgrade runtime command

---

cmd/upgrade.go

Fix upgrade runtime command (#593)

Fix upgrade runtime command (#593)

---

cmd/init.go
cmd/upgrade.go
pkg/kubernetes/upgrade.go

Closes https://github.com/dapr/cli/issues/601

fix preserveUnknownFields upgrade

---

cmd/init.go
cmd/upgrade.go
pkg/kubernetes/upgrade.go

fix preserveUnknownFields upgrade (#602)

---

pkg/kubernetes/upgrade.go

Fix CRD deletions (#624)

---

tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go

Update runtime to RC.2 version

---

cmd/stop.go

remove the extra dot #652

---

cmd/run.go

Receive appRunning channel value if the value false then try to stop daprd and exit
close:#645 

when start app error try to stop daprd process

---

.github/workflows/dapr_cli.yaml

Reverting until we retroactively fix all new linter issue raise by the upgrade

Reverting the golangci-linter upgrade

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
cmd/mtls.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/testdata/statestore.yaml

Added components check and mtls check to e2e tests.
Please reference the issue this PR will close: #662 
closes #671 

Added E2E tests for k8s components and mtls 

---

.github/workflows/self_hosted_e2e.yaml
tests/e2e/standalone/standalone_test.go

Add `dapr stop` e2e test. Should retroactively cover #631 
Also, run standalone tests on MacOS

Stop e2e test

---

tests/e2e/standalone/standalone_test.go

Add e2e tests for `dapr list` in self-hosted mode.

add list self-hosted e2e

---

cmd/invoke.go
cmd/publish.go
tests/e2e/standalone/standalone_test.go

Add a few negative e2e test cases for the --data-file option in invoke & publish.

Add some negative tests for invoke and publish

---

README.md

Update Reference Guide link in README.md to dapr docs website instead of
reference docs removed from this repo in #501.
Please reference the issue this PR will close: #686

Update link to CLI reference in README.md

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
Makefile
go.mod
go.sum

Save the test output for e2e and unit tests as a json file attached to the build job. If we want to scan this data and build a report it will be much much easier than clicking through the github UI.
You can find the JSON test output attached to each run:
https://github.com/dapr/cli/actions/runs/734751808
Please reference the issue this PR will close: #688

Upload test results as a github actions run artifact

---

pkg/kubernetes/upgrade.go
pkg/kubernetes/upgrade_test.go
tests/e2e/kubernetes/kubernetes_test.go

Closes https://github.com/dapr/cli/issues/664.
Reference: https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e

fix reset values on upgrade

---

cmd/run.go
pkg/standalone/list.go
pkg/standalone/run.go
pkg/standalone/run_test.go

adding dapr-http-max-request-size parameter to cli
#699 
Please reference the issue this PR will close: #699 

adding dapr-http-max-request-size parameter to cli

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml
tests/e2e/kubernetes/kubernetes_test.go

Add HA Mode upgrade path tests
Please reference the issue this PR will close: #674 

Add HA mode upgrade path tests

---

.github/workflows/dapr_cli.yaml
.github/workflows/release_notification.yaml

Fix secret to release from org level cred.

Fix secret to release from org level cred.

---

cmd/stop.go
pkg/kubernetes/kubernetes.go
tests/e2e/standalone/standalone_test.go

[NO SQUASH MERGE] Merge master to 1.2

---

pkg/kubernetes/kubernetes.go

Fixes https://github.com/dapr/cli/issues/719.

Fix init -k without --runtime-version

---

pkg/kubernetes/kubernetes.go

fix init -k without --runtime-version (#721)

---

Makefile
go.mod
go.sum

Enables building for M1 ARM Mac
* [] Extended the documentation

Fix build on Darwin Arm64

---

.github/workflows/installdaprwin.yml

Add CI/CD Test for Windows Powershell Installer
To verify the work in #647

Add CI/CD Test for Windows Powershell Installer

---

Makefile
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go
tests/e2e/upgrade/upgrade_test.go

Currently in draft updated to RC.5

update upgrade paths runtime version

---

.github/workflows/kind_e2e.yaml
.github/workflows/upgrade_e2e.yaml

Updating KinD/k8s version to match dapr/dapr#3367.

Update kubernetes version for CLI e2e tests

---

pkg/kubernetes/components.go
pkg/kubernetes/configurations.go
pkg/kubernetes/mtls.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/upgrade/upgrade_test.go

Adding E2E tests to accompany #656
Closes #656 (for real)

Adding tests for `dapr uninstall -k --all`

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml

Pin Go 1.16.6 due to caching

---

pkg/standalone/run.go
pkg/standalone/run_test.go

Cherry picking b3cfa05176f35d313bbf5332e67d691a8656b156 from master to release-1.3

Cherry Pick: Run command: fix bool args passed to daprd (#768)

---

tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go
tests/e2e/upgrade/upgrade_test.go

Will be squash merged to release branch. The release branch will later be merged to master branch preserving the commit history. 

Update runtime to 1.3.0

---

tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go
tests/e2e/upgrade/upgrade_test.go

DO NOT SQUASH MERGE 
DO NOT AUTO MERGE

Merge back from release branch (1.3) (DO NOT SQUASH MERGE)

---

tests/e2e/standalone/standalone_test.go

Signed-off-by: Long Dai <long0dai@foxmail.com>
Fix typos.

tests: fix typos

---

.github/workflows/dapr-bot.yml

Allows anybody to /assign via Dapr Bot
Please reference the issue this PR will close: https://github.com/dapr/dapr/pull/3515

Allows anybody to /assign via Dapr Bot

---

cmd/dashboard.go
utils/utils.go

dapr dashboard add "--address" option, such as dapr dashboard -k -p 9999  --address 0.0.0.0
close: #780 

dapr dashboard add address option

---

.gitignore
tests/e2e/standalone/standalone_test.go
tests/e2e/upgrade/upgrade_test.go

Check upgrade path for runtime RC versions.

e2e for runtime version 1.4.0

---

tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go
tests/e2e/upgrade/upgrade_test.go

Update E2E versions to 1.5.0

---

tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go
tests/e2e/upgrade/upgrade_test.go

Upgrade test for 1.4.4 and 1.5.1 releases

Upgrade test for 1.4.4 and 1.5.1 releases

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
cmd/init.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go

Added code to get the latest Dapr dashboard version automatically for E2E tests
Please reference the issue this PR will close: #832 

Added code to pull dashboard version automatically for E2E tests

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

update e2e tests, upgrade tests to version 1.6.0

update e2e tests, upgrade tests to version 1.6.0

---

.github/workflows/self_hosted_e2e.yaml
README.md
cmd/init.go
pkg/standalone/standalone.go
tests/e2e/standalone/standalone_test.go

Added support for providing image-repository url with dapr init command
this PR will close: #869 

Adding support for image-repository url with dapr init

---

cmd/components.go
cmd/configurations.go
cmd/dashboard.go
cmd/list.go
cmd/logs.go
cmd/mtls.go
cmd/status.go
cmd/upgrade.go
pkg/kubernetes/mtls.go
tests/e2e/common/common.go

Show warning for certificate expiry on all kubernetes related commands
Please reference the issue this PR will close: #893 

Include certificate expiry check in all kubernetes commands

---

.devcontainer/devcontainer.json

Add a devcontainer for easy development and debugging.
Please reference the issue this PR will close: #202
* (NA) Code compiles correctly
* (NA) Created/updated tests
* (NA) Extended the documentation

Add a devcontainer for cli repository

---

Makefile
pkg/print/print.go
pkg/standalone/run.go
tests/e2e/standalone/standalone_test.go

Signed-off-by: Mukundan Sundararajan <msundar.ms@outlook.com>
Please reference the issue this PR will close: #897

fix log as json flag

---

pkg/standalone/invoke.go
tests/e2e/standalone/standalone_test.go

This PR adds HTTP status code handling in `dapr invoke`.
Please reference the issue this PR will close: #909
* (NA) Extended the documentation

Handle HTTP status checks in invoke

---

tests/e2e/common/common.go
tests/e2e/upgrade/upgrade_test.go

Fix for flaky upgrade related tests
Please reference the issue this PR will close: #794 
* [NA] Created/updated tests
* [NA] Extended the documentation

Fix for flaky upgrade test

---

docs/development/development.md

Fixing the broken link
_Updated the correct link for MinGW_
Please reference the issue this PR will close: #922 

fixing the broken link of MinGW

---

pkg/version/version.go
pkg/version/version_test.go

Please reference the issue this PR will close: #853

fix get latest version

---

cmd/components.go
cmd/configurations.go
cmd/dapr.go
cmd/init.go
cmd/list.go
pkg/kubernetes/components.go
pkg/kubernetes/components_test.go
pkg/kubernetes/configurations.go
pkg/kubernetes/configurations_test.go
pkg/kubernetes/list.go
tests/e2e/common/common.go
tests/e2e/testdata/statestore.yaml

dapr list/components/configuration cmd add --namespace and --all-namespace flag for filter define namespace resource,and output list with namespace info.
closes #786 

dapr cli list components configuration add namespace flag

---

README.md
cmd/components.go
cmd/configurations.go
cmd/init.go
cmd/list.go
pkg/standalone/standalone.go
tests/e2e/common/common.go

Signed-off-by: Mukundan Sundararajan <msundar.ms@outlook.com>
Fixed examples. Added examples to readme. Fixed tests for the changed output.
related to #786 #640

Fix examples and print preview feature warnings

---

.github/workflows/self_hosted_e2e.yaml
pkg/standalone/standalone.go
pkg/standalone/standalone_test.go
utils/utils.go

Some code refactoring for image pull logic on dapr init
related to #726 

 Switching default to Docker Hub and Minor code refactoring

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
README.md
cmd/run.go
pkg/standalone/run.go
pkg/standalone/run_test.go
tests/e2e/standalone/standalone_test.go

Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>
Update api logging feature - Changed from api-log-level to enable-api-logging.

Changed API logging feature on CLI

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Updating dapr to v1.7.0-rc.3

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
pkg/standalone/bundle_test.go
tests/e2e/upgrade/upgrade_test.go

Update to 1.7.0 runtime

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
README.md
cmd/init.go
cmd/renew_certificate.go
cmd/run.go
go.mod
go.sum
pkg/kubernetes/mtls.go
pkg/standalone/bundle.go
pkg/standalone/bundle_test.go
pkg/standalone/docker.go
pkg/standalone/run.go
pkg/standalone/run_test.go
pkg/standalone/standalone.go
pkg/standalone/standalone_test.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go
tests/e2e/upgrade/upgrade_test.go

[NO SQUASH MERGE] Merge release-1.7 to master

[NO SQUASH MERGE] Merge release-1.7 to master

---

.devcontainer/devcontainer.json

Bump dev container to 0.1.7
Please reference the issue this PR will close: Endgame

Bump dev container to 0.1.7

---

.github/workflows/self_hosted_e2e.yaml

Upgrades the action version that contains a fix related to MacOS.
Please reference the issue this PR will close: #965

Upgrade actions-setup-docker in E2E - Self Hosted workflow

---

.github/workflows/dapr_cli.yaml

Bumping golngci-lint-action to include lates fix - https://github.com/golangci/golangci-lint-action/releases/tag/v3.2.0

bumping golangci-lint-action

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml

Specific workflows can be skipped during PR check for changes in non impacting assets.
#925
Please reference the issue this PR will close: #925

Specific workflows can be skipped during PR check for changes in non impacting assets

---

.golangci.yml
cmd/dashboard.go
pkg/standalone/standalone.go
tests/e2e/common/common.go

Fix master build and linter issues

fix linter issues

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Upgrading runtime to 1.8.0.-rc.3

Upgrading runtime to RC.3

---

.devcontainer/devcontainer.json
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Signed-off-by: Pravin <ppushkar@microsoft.com>
Update runtime version and dev container version

update runtime version and dev container version

---

.github/workflows/dapr_cli.yaml
.github/workflows/self_hosted_e2e.yaml

Pinning macos version to 10.15.

Pinning macos to 10.15 version

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

Fix Redis docker image to version 6.

Update redis version to redis 6 (#1045)

---

cmd/init.go
cmd/upgrade.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/upgrade.go
pkg/standalone/standalone.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/init_test.go
tests/e2e/upgrade/upgrade_test.go
utils/utils.go

Signed-off-by: shivam <shivamkm07@gmail.com>
It adds support for mariner images in dapr init
Please reference the issue this PR will close: #1004 

Adding mariner support in dapr init

---

pkg/standalone/standalone.go

Add ProxyFromEnvironment in downloadFile method.
Please reference the issue this PR will close: [#1043 ](https://github.com/dapr/cli/issues/1043)

Add ProxyFromEnvironment in downloadFile method

---

README.md

Signed-off-by: shivam <shivamkm07@gmail.com>
Adding `--image-variant` in Readme

Adding mariner image in Readme

---

.github/workflows/dapr_cli.yaml
go.mod
go.sum

Fix vuln go dep found.
Please reference the issue this PR will close: #1061

Fix vuln go dep

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml
Makefile
docs/development/development.md
go.mod

Go version updated
Please reference the issue this PR will close: #1060

upgrade go version

---

.github/workflows/kind_e2e.yaml

update kind k8s version to latest

update kind k8s version to latest

---

.github/workflows/kind_e2e.yaml
.github/workflows/upgrade_e2e.yaml

Fix KinD E2E workflow and E2E upgrade path workflow KinD versions 

fix e2e workflow and upgrade e2e kind versions

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
pkg/kubernetes/upgrade.go
tests/e2e/upgrade/upgrade_test.go

Wrt https://github.com/dapr/dapr/pull/5299

Remove plug comp crd init. Move to latest commit in go-sdk.

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Update Dapr RC to 1.9.0-rc.5

---

cmd/run.go
pkg/standalone/run.go
pkg/standalone/run_test.go

nit PR, addresses comment from #1083, update `appHealthEnabled` => `enableAppHealth`
Related, #1082

(nit) Update app health check enabled flag

---

cmd/dashboard.go
pkg/metadata/metadata.go

Fixes dashboard scheme which was missed when changing it to `net.JoinHostPort`
Also fixed a linter issue that popped up.
Please reference the issue this PR will close: #1091 

fix dashboard scheme. fix linter issue

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

Update redis image to redis:6
Please reference the issue this PR will close: #1094

Update redis image to redis:6

---

go.sum
pkg/standalone/uninstall.go

Please reference the issue this PR will close: #1093

Delete remove image logic from uninstall

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Release 1.9

---

pkg/kubernetes/kubernetes.go

Signed-off-by: shivam <shivamkm07@gmail.com>
merging new fixes from 1.9 to master

fix kubernetes init to pick correct runtime version (#1103)

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml

update golang version

---

cmd/completion.go

Add support for fish shell completion.
closes #879 

feat: support fish shell completion

---

.github/workflows/fossa.yml
pkg/kubernetes/status.go
pkg/kubernetes/status_test.go

- Fix version parsing from docker image
Please reference the issue this PR will close: #1113

fix getting control plane version

---

pkg/standalone/run.go

Convert uppercase to lowercase while generating app ID.
Please reference the issue this PR will close: #1136

Fix App ID generation

---

cmd/run.go
go.mod
pkg/standalone/runfileconfig/run_file_config_parser.go
utils/utils.go
utils/utils_test.go

Please reference the issue this PR is related to: #1143

find dapr.yaml in dirpath when dapr run -f <dirpath> is executed

---

cmd/dapr.go
cmd/invoke.go
cmd/publish.go
cmd/run.go
cmd/stop.go
pkg/standalone/list.go
pkg/standalone/stop.go
pkg/standalone/stop_windows.go
tests/e2e/standalone/stop_test.go

Please reference the issue this PR will close: 
closes #1165 
closes #1153

Dapr stop and list changes for dapr run -f

---

pkg/standalone/run.go
pkg/standalone/runfileconfig/run_file_config.go
pkg/standalone/runfileconfig/run_file_config_parser.go
pkg/standalone/runfileconfig/run_file_config_parser_test.go
pkg/standalone/testdata/runfileconfig/test_run_config.yaml
pkg/standalone/testdata/runfileconfig/test_run_config_empty_app_dir.yaml
pkg/standalone/testdata/runfileconfig/test_run_config_invalid_path.yaml
pkg/standalone/testdata/runfileconfig/test_run_config_precedence_rule.yaml
pkg/standalone/testdata/runfileconfig/test_run_config_precedence_rule_dapr_dir.yaml
tests/e2e/testdata/run-template-files/dapr.yaml
tests/e2e/testdata/run-template-files/empty_app_command.yaml
tests/e2e/testdata/run-template-files/env_var_not_set_dapr.yaml
tests/e2e/testdata/run-template-files/no_app_command.yaml
tests/e2e/testdata/run-template-files/wrong_emit_metrics_app_dapr.yaml

To be consistent with Dapr, snake_case in yaml run template is changed to camelCase.
Please reference the issue this PR will close: #1182 

change snake_case run template yaml to camelCase

---

cmd/dashboard.go
pkg/standalone/dashboard.go
pkg/standalone/dashboard_test.go
utils/utils.go

Please reference the issue this PR will close: #1188

Fix dashboard port conflict message and allow starting on random port

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml

Exclude PR checks on pre-released dapr versions for E2E tests.

exclude E2E tests on pre-released dapr in PR checks

---

.devcontainer/devcontainer.json

Updates the dev container to the latest one from the runtime, and adds some useful settings.

Update dev container

---

install/install.ps1

correct spelling

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
pkg/standalone/common.go
pkg/standalone/common_test.go
tests/e2e/standalone/init_run_custom_path_test.go
tests/e2e/upgrade/upgrade_test.go

Update runtime version to 1.10.0-rc.3.
Minor nits specified in #1203 

update runtime version to 1.10.0-rc.3. Minor nit fixes

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Update runtime to rc.4

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

update runtime to RC.6

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Point to the latest Dapr RC, v1.10.0-rc.8
NA, endgame.

Upgrade Dapr runtime to v1.10.0-rc.8

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Update Dapr runtime to 1.10.0-rc.9

Update Dapr runtime to 1.10.0-rc.9

---

.github/workflows/dapr_cli.yaml

Fix token issue

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml
pkg/standalone/dashboard_test.go
pkg/standalone/runfileconfig/run_file_config_parser_test.go
pkg/standalone/standalone_test.go
tests/e2e/standalone/init_negative_test.go
utils/utils_test.go

Parallel exec for UTs and cache go dep

---

.github/workflows/dapr_cli.yaml
.golangci.yml
pkg/standalone/uninstall.go

Upgrade golangci lint to 1.51.2

Upgrade linter version to the latest

---

.github/workflows/dapr_cli.yaml
Makefile

Remove govulncheck from workflow and add a make recipe for it. 
Related to https://github.com/dapr/cli/pull/1233#issuecomment-1468110052

remove govulncheck from workflow

---

dev-container-feature/src/dapr-cli/NOTES.md
dev-container-feature/src/dapr-cli/README.md

Update README as per https://github.com/dapr/cli/pull/1233#issuecomment-1478754647
~Please reference the issue this PR will close: #_[issue number]_~

Update dev container feature docs to include docker

---

cmd/run.go
tests/e2e/standalone/run_test.go

Please reference the issue this PR will close: #1271

fix appID reference

---

cmd/init.go
cmd/upgrade.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/renew_certificate.go
pkg/kubernetes/uninstall.go
pkg/kubernetes/upgrade.go
pkg/version/version.go
pkg/version/version_test.go

Handles Dapr Dashboard's Helm chart separately.
Related to https://github.com/dapr/dapr/issues/4724

Installs,uninstalls,upgrade dapr-dashboard separately when applicable.

---

cmd/run.go
pkg/standalone/list.go
pkg/standalone/runfileconfig/run_file_config.go
tests/e2e/standalone/run_template_test.go
tests/e2e/standalone/stop_with_run_template_test.go
tests/e2e/testdata/run-template-files/dapr.yaml

This adds a name property to the template which shows up in yaml and json outputs of list command. 
Please reference the issue this PR will close: #1204 

Add name template

---

.github/workflows/self_hosted_e2e.yaml

Timeout if podman is not installed within specified time.

add timeout for install podman step

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go
pkg/standalone/uninstall.go

I noticed a small mistake in the variable names so this is a quick PR to fix 😃

Fixed small typo in variables and function call

---

cmd/run.go
pkg/standalone/run.go
pkg/standalone/runfileconfig/run_file_config.go
pkg/standalone/runfileconfig/run_file_config_parser.go

Please reference the issue this PR will close: #1293

Move log destination flag to sharedRunConfig

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
go.mod
go.sum
pkg/kubernetes/dashboard_chart_test.go
tests/e2e/upgrade/upgrade_test.go

Release 1.11

---

README.md
docs/development/release.md

add release doc

---

Makefile
pkg/kubernetes/logs.go
pkg/kubernetes/run.go
pkg/kubernetes/stop.go
tests/e2e/common/common.go
tests/e2e/kubernetes/clean_env.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/kubernetes/run_template_test.go
tests/e2e/standalone/commands.go
tests/e2e/testdata/run-template-files/dapr-k8s.yaml
tests/e2e/upgrade/upgrade_test.go

To be merged after #1333 
Example run https://github.com/dapr/cli/actions/runs/6068518369/job/16461582317#step:14:1368 

E2E test for multi app run k8s

---

pkg/kubernetes/kubernetes.go
pkg/kubernetes/run.go

Add the default appconfig if present. 
Please reference the issue this PR will close: #1351 

add appconfig default config for dev mode multi-app run k8s

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/upgrade_e2e.yaml

Fix Golang version to 1.21.8 https://groups.google.com/g/golang-announce/c/5pwGVUPoMbg?pli=1

fix golang version

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml
go.mod
go.sum
tests/e2e/upgrade/upgrade_test.go

Update Dapr runtime version for 1.13 release
Please reference the issue this PR will close: n/a

Update Dapr runtime version for 1.13 release.

---

pkg/kubernetes/kubernetes.go

Fixes issue described in https://github.com/overleaf/overleaf/issues/1240.

update redis version

---

cmd/stop.go

Fix a typo

---

go.mod

release: pin go to 1.23.5

---

tests/e2e/common/common.go

Cherry-pick for the release-1.15 branch from https://github.com/dapr/cli/pull/1488

Fix scheduler pod count for 1.15 version when testing master and latest

---

pkg/kubernetes/kubernetes.go

Moves deprecated Redis repo link to the legacy bitnami repo.

Fix redis version
