pkg/kubernetes/client.go

Adding support for cli users that are supplying kubeconfig using `KUBECONFIG` environment variable. Currently, `dapr` cli fails to deploy to Kubernetes if the user doesn't have a valid kubeconfig in their `~/.kube/config` directory. 

kubernetes: adding support for KUBECONFIG environment variable

---

install/install.ps1

Old version of powershell uses TLS 1.0 as a default secure protocol. This PR forces to support TLS 1.2, 1.1, and 1.0.
#166 

[Windows Install Script] Support TLS 1.2/1.1/1.0

---

install/install.ps1

Docker Desktop for Windows supports both Linux and Windows containers modes. When running Dapr via CLI as a standalone mode, dapr cli starts the container to run placement service. container image is built for linux container. therefore, Windows user needs to ensure that they are using Linux containers mode. 
This PR has windows install script to print out the message to ensure docker desktop use linux containers mode.
https://github.com/dapr/docs/issues/162
https://github.com/dapr/docs/pull/163

[Windows install script] add message to ensure docker desktop use linux container mode

---

cmd/uninstall.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go

Remove all container when user runs `dapr uninstall`.  This is: https://github.com/dapr/cli/issues/176
https://github.com/dapr/cli/issues/176
Please reference the issue this PR will close: #_176_

dapr uninstall should remove all containers

---

cmd/run.go

This removes the --kubernetes flag from dapr run, which was not used and confusing.  A comment was added to usage to point the user at helm charts, which is the preferred way.
https://github.com/dapr/cli/issues/195
Please reference the issue this PR will close: #_195_

Remove --kubernetes option from dapr run

---

cmd/init.go
cmd/uninstall.go
pkg/standalone/uninstall.go

This PR cleans the `daprio/dapr` image on `uninstall` and `init`, allowing the Docker Daemon to re-pull the image.
Closes #204

remove Dapr placement image on uninstall and init

---

cmd/init.go

On `dapr init`, Redis is not installed if a previous image already exists, because a fixed container name has been introduced in [this](https://github.com/dapr/cli/pull/192) PR.
This change removes any existing redis container on init.

remove redis on local init

---

cmd/init.go
pkg/standalone/run.go
pkg/standalone/standalone.go
utils/utils.go

Add an `--install-path` arg to allow users to install Dapr to a different dir.
Also, add more detailed message if the install to /usr/local/bin (the default) fails because of permissions.
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/79, https://github.com/dapr/cli/issues/168

Allow alternate install path

---

pkg/standalone/run.go

Make the auto-generated files in the "components" dir genericly named to make behavior less confusing.
see discussion at: https://github.com/dapr/docs/issues/254
Please reference the issue this PR will close: #_[254]_

Make local file names generic

---

cmd/logs.go
pkg/kubernetes/logs.go

Added `logs` command to `dapr`
```
dapr logs -h
Gets Dapr sidecar logs for an app in Kubernetes
Usage:
dapr logs [flags]
Flags:
-a, --app-id string      The app id for which logs are needed
-h, --help               help for logs
--kubernetes         Only works with a Kubernetes cluster (default true)
-n, --namespace string   (optional) Kubernetes namespace in which your application is deployed. default value is 'default'
-p, --pod-name string    (optional) Name of the Pod. Use this in case you have multiple app instances (Pods)
```
Issue #189 
- `dapr logs --app-id nodeapp --kubernetes` - fetch `daprd` logs from `nodeapp`
- `dapr logs --app-id nodeapp --pod-name nodeapp-8544f8bf6b-cvz2x …

[WIP] Added 'logs' command to dapr cli

---

pkg/standalone/run.go

With this change, user has to provide 'enable-actorstore' to configure actor state persistence in actors.
Closes #230 

Enable actorStateStore by default in standalone mode

---

cmd/invoke.go
cmd/invokeGet.go
cmd/invokePost.go
pkg/invoke/invoke.go

This proposal adds support for HTTP GET to invoke commands. In order to avoid breaking existing scripts using Invoke, I added commands InvokeGet and InvokePost and updated the description to make Invoke obsolete. I also refactored pkg/invoke to accommodate the new commands.
Please reference the issue this PR will close: #224 
* [x ] Code compiles correctly

Add InvokeGet and Post, refactor Invoke.

---

install/install.ps1

If a user has both PSCX and Microsoft.Powershell.Archive installed on their machine, the Expand-Archive call defaults to PSCX's version of Expand-Archive, with using -OutputPath instead of -DestinationPath. By specifying the module name before the call, we can ensure the proper version is always called and prevent an error for some users.
This will resolve issue #221
Modified install.ps1 script to change an error that occurs for users who have Powershell Community Extensions installed.
Please reference the issue this PR will close: #221
* [N/A] Created/updated tests
* …

Resolve #221 Installation Failure

---

pkg/standalone/stop.go

Add /T to taskkill on Windows. 
The issue is that dapr stop operates on the dapr instance that is hosting the app we want to stop. On MacOS/Linux we send kill and dapr has a handler for this to kill its children daprd and app. On windows, taskkill sends WM_CLOSE. Rather than handling it the same way as the kill signal handlers, it's easier to just add /T to the taskkill command, which will terminate children processes.
Please reference the issue this PR will close: #222 

#222 dapr stop does not work on windows

---

pkg/version/version.go

This minor, cosmetic fix ensures the output of `--version` ends with a newline even when there's no runtime installed. Perhaps there is a better way, like ending L26 with a newline and chomping the output of `daprd --version`.
Seeing this is a minor fix in a somehow obscure use case (I hit this bug when `dapr init` failed on me, so I still had no runtime version output) I didn't want to waste the team's time with an issue.
I built this with `REL_VERSION=foo make release` with no warnings and confirmed the built binary outputs an endline when `daprd` is not present in `PATH`.
Apologies for writing more in this text than in the actual code.

Cosmetic endline fix for --version

---

pkg/standalone/mtls_config.go
pkg/standalone/run.go

This PR reads the configuration file, if supplied, and enables mTLS on `daprd` with the default address for Sentry.

enable mTLS support for CLI

---

.gitignore
go.mod
pkg/standalone/run.go
pkg/standalone/run_test.go

Warning about yaml files being overwritten.
Use filepath.Join() instead of path.Join() in run.go
Started some unit tests for standalone/run.go
Please reference the issue this PR will close: #262 

Warn yaml + some unit tests

---

pkg/kubernetes/client.go

I am unable to execute --kubernetes commands in windows as it splits wrong the home path.
With this change, if only one delimiter is found and it belongs to the user home path and also the KUBECONFIG env var is the same as the file path join of the user home kube config, no split is executed
#277 

Fix client initialization when KUBECONFIG OS path has : delimiter (#277)

---

README.md
cmd/run.go
go.mod
go.sum
pkg/standalone/run.go
pkg/standalone/run_test.go

Allows run without app and daemon mode for Unix-based OS.
Run without app:
dapr run --app-id myid --port 3005 --grpc-port 50001
dapr run
Please reference the issue this PR will close: #248 

Allows run without app

---

cmd/init.go
cmd/list.go
cmd/logs.go

Add --kubernetes shorthand (k) to list, init and logs cli commands.
Other commands like components, configuration and mtls already have this shorthand
#267

Add Kubernetes shorthand k to init, list and logs cli commands #267

---

pkg/standalone/standalone.go

When the redis container is created, the potential custom docker
network is appended to the container name. This change uses the
same convention when checking that the redis container is running.
Fixes #302.

Use the full container name when checking redis

---

Makefile

Adds tar.gz for Homebrew on Catalina. It will allow installation via binary instead of source code on Catalina macOS.
Please reference the issue this PR will close: #171 

Adds tar.gz for Homebrew.

---

README.md
cmd/logs.go
cmd/status.go
pkg/kubernetes/list.go
pkg/kubernetes/logs.go
pkg/kubernetes/pods.go
pkg/kubernetes/status.go

Closes #312 
This PR allows a user to see the Dapr control plane status when running on Kubernetes.
Command: `dapr status -k` or `dapr status --kubernetes`.
Output example: (2 services running, 2 failing):
```
NAME                   NAMESPACE    HEALTHY  STATUS                      VERSION  AGE  CREATED              
dapr-operator          dapr-system  False    Waiting (CrashLoopBackOff)  0.6.0    2d   2020-04-04 11:19.39  
dapr-placement         dapr-system  True     Running                     0.6.0    2d   2020-04-04 11:19.39  
dapr-sentry            dapr-system  False    Terminated                  0.6.0    2d   2020-04-04 11:19.39  
dapr-sidecar-injector  dapr-system  True     Running                     0.6.0    2d   2020-04-04 11:19.39 
```

Add dapr control plane status for Kubernetes

---

cmd/init.go
pkg/kubernetes/kubernetes.go

To support honoring the --runtime-version flag for kubernetes init
Closes #307

Adding support for --runtime-version flag for dapr init k8s

---

cmd/run.go

The output of `dapr run --help` states that "warning" is a valid value for --log-level, it should be "warn"
https://github.com/dapr/cli/issues/319

Minor fix to log-level help text for `dapr run`

---

pkg/standalone/run.go

Metadata name should be pubsub in default generated pubsub component.
Please reference the issue this PR will close: #322

metadata name should be pubsub

---

cmd/run.go
docs/reference/dapr-run.md
pkg/standalone/run.go
pkg/standalone/run_test.go

This PR adds `--components-path` flag to `dapr run` command
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dapr/cli/326)

Add flag to provide custom components directory path for dapr run

---

pkg/standalone/uninstall.go

This PR adds a more verbose log on the failure of container uninstall. 
The error message would look like this:
```
➜  dapr uninstall
ℹ️  Removing Dapr from your cluster...
WARNING: could not delete run data file
❌  Error removing Dapr: uninstall failed 
could not remove dapr_placement container: Error: No such container: dapr_placement
could not remove dapr_redis container: Error: No such container: dapr_redis
```
This PR will close: https://github.com/dapr/cli/issues/330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dapr/cli/333)

More verbose log on failure of container uninstall

---

pkg/standalone/standalone.go
pkg/standalone/uninstall.go
utils/utils.go

This PR adds a check if docker is running while doing `dapr uninstall` similar to `dapr init`. 
If docker is not running, the error message would look like this: 
```
➜  dapr uninstall
ℹ️  Removing Dapr from your cluster...
WARNING: could not delete run data file
❌  Error removing Dapr: uninstall failed 
could not connect to Docker. Docker may not be installed or running
```
If docker is running, the error message would look like this: 
```
➜  dapr uninstall
ℹ️  Removing Dapr from your cluster...
WARNING: could not delete run data file
❌  Error removing Dapr: uninstall failed 
could not remove dapr_placement container: Error: No such container: dapr_placement
could not remove dapr_redis container: Error: No such container: dapr_redis
```
This PR will close: …

Check if docker is running on uninstall

---

cmd/run.go
docs/reference/dapr-run.md
pkg/standalone/run.go
pkg/standalone/run_test.go

Now it´s possible to run `dapr run` with the following flag: `--enable-dev-secretstore` which will enable the new json secret store: https://github.com/dapr/components-contrib/pull/328
Please reference the issue this PR will close: #344

Implementing #344

---

README.md
cmd/stop.go
docs/reference/dapr-stop.md

I added the functionality of stopping multiple apps using `dapr stop`.
```
dapr stop pythonapp nodeapp blahblah
✅  app stopped successfully: pythonapp
✅  app stopped successfully: nodeapp
❌  failed to stop app id : couldn't find app id blahblah
```
This also works.
```
dapr stop pythonapp --app-id blahblah
✅  app stopped successfully: pythonapp
❌  failed to stop app id : couldn't find app id blahblah
```
Please reference the issue this PR will close: #247 
I may need some advice on what tests and documentation to write for this functionality.

Enable Dapr to stop multiple apps

---

README.md
cmd/run.go
docs/reference/dapr-run.md
docs/reference/dapr-uninstall.md
pkg/standalone/common.go
pkg/standalone/run.go
pkg/standalone/run_test.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go
pkg/version/version.go

This is to run zipkin and enable tracing by default on `dapr init`
This also deletes the `.dapr` folder on `dapr uninstall --al`
Working on the docs now.
Please reference the issue this PR will close: #342 

Add Zipkin on dapr init. Add tracing config, zipkin component on init.

---

Makefile

Add timeout for linter run. Similar to core dapr repo.
This was found as part of the previous run where the linter continued to run even after 20m in the workflow. 

Add timeout for linter

---

README.md
cmd/init.go
cmd/uninstall.go
docs/reference/dapr-init.md
docs/reference/dapr-uninstall.md
pkg/standalone/common.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go

Remove uninstall all from init path. Add install path arg to uninstall cmd. Cleanup binaries, archive correctly.
Removed `uninstall(true)` from standalone init path. 
Removed archive, binary from default `.dapr` folder. 
Remove binary from default installation path or custom installation path specified by `--install-path` arg. 
Do not create/run `dapr_zipkin`, `dapr_redis` containers if already exists rather start it if already exists. 
Do not initialize dapr again if `daprd` is installed or `dapr_palcement` exists/running.
Please reference the issue this PR will close: #380 
Please make sure you've completed the relevant tasks for this PR, out of the …

Fix Standalone dapr init behavior.

---

cmd/dashboard.go
docs/reference/dapr-dashboard.md

Added docs for `dapr dashboard` command, and fixed a grammatical error.
This PR will close: #341

Added documentation for dapr dashboard

---

cmd/dashboard.go
docs/reference/dapr-dashboard.md
pkg/kubernetes/client.go
pkg/kubernetes/pods.go

* Removed user requirement to apply dashboard to their cluster, rely on 'dapr init -k' or helm install
* Added search for dashboard namespace: searches namespaces dapr-system and default for dashboard pod
* Added method to check if pod exists in namespace
* Added -n flag for dapr dashboard command to allow the user to supply a namespace
* Updated documentation for dashboard command
closes #389 
References: https://github.com/dapr/dapr/pull/1752

Dashboard integration: Updating user requirements and port-forwarding correct namespace

---

README.md
cmd/completion.go

For #197, added a feature to support "auto-completion" for Dapr CLI using the Tab key. In addition to that, updated the README.md to introduce the subcommand `dapr completion`.
Please reference the issue this PR will close: #197 
I didn't come up with an idea to make this test code, so I checked the [kubectl repo](https://github.com/kubernetes/kubectl/tree/master/pkg/cmd/completion), but it looks that it doesn't test for the completion part.

Added command completion feature to Dapr CLI

---

README.md
cmd/uninstall.go
docs/reference/dapr-init.md
docs/reference/dapr-uninstall.md
pkg/kubernetes/uninstall.go

* Fixed uninstall command to take version in kubernetes mode. It is needed when installed through specific version, and it helps testing release candidate builds.
* Added --runtime-version flag to `dapr uninstall`
* Added -k shorthand to `dapr uninstall`
closes #395 

Fixed uninstall command to take the version in kubernetes mode to uninstall

---

.github/workflows/release_notification.yaml

Notifies homebrew repo about a new release of Dapr Cli. This avoids busy waiting every 5 min for a new release.
Please reference the issue this PR will close: #328

Notify dapr/homebrew-tap on new release.

---

pkg/standalone/standalone.go

* Fixed bug where `dapr init` tells the user to export their paths twice
None

Fixing duplicate dapr init user message on linux

---

README.md
cmd/mtls.go
pkg/kubernetes/client.go
pkg/kubernetes/mtls.go

This PR does the following:
1. Adds a command that helps users export their TLS certificates from a kubernetes cluster
2. Fixes race condition bugs for the k8s/dapr clients
Closes #419

Add certificate export command

---

README.md
cmd/mtls.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/mtls.go

This PR allows an operator or developer to check when their Root Certificate expires.
On the way, @youngbupark and I realized there's a bug with the `https://dapr.github.io/dapr-helm-charts.io` chart repo and reverted back to the correct one with this PR.
Once the issue is fixed we can change back.
Usage:
```bash
$ dapr mtls expiry
Root certificate expires in 8759 hours. Expiry date: 2021-08-13 23:55:36 +0000 UTC
```

Add root cert expiry check command

---

.github/workflows/dapr_cli.yaml
Makefile

Remove `--fix` from linter 
`--fix` does autofix of code and changes code for linting. Should be removed as it has been done for dapr/dapr and dapr/components-contrib.
Similarly for the 2 repos, lint is not run in windows or arm nodes, making the change here as well. 
First part in upgrading to 1.30.0.
Please reference the issue this PR will close: #447 

Remove --fix in make lint

---

cmd/run.go
utils/utils.go

If app does not expose a port, cli will wait for runtime before starting app.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1933

Waits for dapr sidecar before running app without port.

---

cmd/status.go
pkg/kubernetes/pods.go
pkg/kubernetes/pods_test.go
pkg/kubernetes/status.go
pkg/kubernetes/status_test.go

Add dashboard to status command. 
Fail gracefully on error. 
Made the status command testable and added unit tests for the same. 
For the other commands that use `ListPods` need a separate task to make them unit testable and add test. 
Please reference the issue this PR will close: #472 #471 

Add dashboard to status command. Fail gracefully on error.

---

.codecov.yaml

Currently, the CodeCov/patch is too strict and would fail PRs if not meeting a certain threshold (for example https://github.com/dapr/cli/pull/447). This PR tunes that down until we bring coverage to that point before making a threshold requirement.

Tune CodeCov to not fail PRs

---

.github/workflows/dapr_cli.yaml

https://nvd.nist.gov/vuln/detail/CVE-2020-15228 advises that `setenv` and `add-path` are not secure, so they will be disabled very shortly on workflows. This changes `set-env` to the recommended upgrade.
Please reference the issue this PR will close: #NA

Remove set-env usage

---

cmd/invoke.go
cmd/invokeGet.go
cmd/invokePost.go
cmd/publish.go
pkg/metadata/metadata_test.go
pkg/standalone/client.go
pkg/standalone/invoke.go
pkg/standalone/invoke_test.go
pkg/standalone/list.go
pkg/standalone/publish.go
pkg/standalone/publish_test.go
pkg/standalone/testutils.go

Make the publish, invoke testable. 
Make List implement a receiver. 
Add unit tests for publish and invoke. 
Add testutils package, defining utilities for testing. 
Output: 
Using quickstarts pub-sub 
```
./dist/darwin_amd64/release/dapr publish --topic A --pubsub pubsub --data '{ "message": "This is a test edge ver 2" }'
✅  Event published successfully
Output: 
== APP == A:  {
== APP ==   id: 'e0792cec-2e93-46b7-999c-2f0ff3dd8130',
== APP ==   source: 'node-subscriber',
== APP ==   type: 'com.dapr.event.sent',
== APP ==   specversion: '1.0',
== APP ==   datacontenttype: 'application/json',
== APP ==   data: { message: 'This is a test edge ver 2' },
== APP ==   subject: '00-747e47361df80a76cab6bb5ae16c3a4b-b767ff08348189ec-01',
== APP ==   topic: 'A',
== APP ==   pubsubname: 'pubsub'
== …
```

Add UTs for publish and invoke

---

install/install.ps1

Executing Install.ps1 will fail if DaprRoot contains spaces
eg:
```powershell
./Install.ps1 -DaprRoot ` C:\Program Files\dapr\`
```
#513 

Support path that contains spaces

---

pkg/standalone/list.go

Requirement to detect metrics enabled for standalone mode in Dashboard.
Does not output new property.
Please reference the issue this PR will close: https://github.com/dapr/dashboard/issues/103

Returns metrics enabled for standalone mode.

---

cmd/run.go

Remove unused image flag and remove kubernetes code from run command.
```
Run Dapr's sidecar and (optionally) an application. Supported Platforms: Self-hosted mode.
Usage:
dapr run [flags]
Examples:
Run a Java application:
dapr run --app-id myapp -- java -jar myapp.jar
Run a NodeJs application that listens to port 3000:
dapr run --app-id myapp --app-port 3000 -- node myapp.js
Run a Python application:
dapr run --app-id myapp -- python myapp.py
Run sidecar only:
dapr run --app-id myapp
Flags:
-a, --app-id string                   The id for your application, used for service discovery
--app-max-concurrency int         The concurrency level of the application, otherwise is unlimited (default -1)
-p, --app-port int                    The port your application is listening on (default -1)
-P, …
```

remove image flag from run command.

---

README.md
cmd/init.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go

Changes made: 
1. remove redis-host flag and environment var binding. 
2. remove install-path environment binding, since that flag is no longer there. 
3. fix uninstall when network specified, check for the right container name and remove it.
4. print right container name on dapr init when network specified. 
5. write configuration files with network aliases when network specified, localhost otherwise.
```
$  ./dist/darwin_amd64/release/dapr init --network mynet
⌛  Making the jump to hyperspace...
→  Downloading binaries and setting up components...
Dapr runtime installed to ~/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
export PATH=$PATH:~/.dapr/bin
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been …
```

Remove redis-host flag, fix configs and uninstall with network flag.

---

cmd/run.go

Fixes https://github.com/dapr/cli/issues/484
This PR preserves the output format from the `daprd` process. After this change, logs now look like this:
<a href="https://ibb.co/80xnK5m"><img src="https://i.ibb.co/g3WbjTr/Screen-Shot-2020-12-15-at-10-37-56-AM.png" alt="Screen-Shot-2020-12-15-at-10-37-56-AM" border="0"></a>

Preserve daprd log output

---

install/install.sh

Until we have a darwin-arm64 build available, users can still run dapr cli on M1 macs using the amd64 compatibility layer. This PR allows our install script to go ahead and install the darwin-amd64 binaries on darwin-arm64.
Please reference the issue this PR will close: #570
```bash
% curl -fsSL https://raw.githubusercontent.com/wcs1only/cli/mac_os_arm64/install/install.sh | /bin/bash -s 1.0.0-rc.3
The darwin_arm64 arch has no native binary, however you can use the amd64 version so long as you have rosetta installed
Use 'softwareupdate --install-rosetta' to install rosetta if you don't already have it
Dapr CLI is detected:
CLI version: 1.0.0-rc.3 
Runtime …
```

Add support for M1 macs with amd64 compatibility layer (#570)

---

README.md
cmd/upgrade.go
go.mod
pkg/kubernetes/upgrade.go
pkg/kubernetes/upgrade_test.go

This PR adds a `dapr upgrade -k` command that greatly simplifies the Dapr upgrade experience.
This PR handles CRD updates and certificate exports for zero downtime upgrades.
Closes https://github.com/dapr/cli/issues/560

Add dapr upgrade command

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

The --slim argument will now create $HOME/.dapr/config.yaml
Please reference the issue this PR will close: #556
```bash
willardstanley@Willards-MacBook-Pro cli % ./dist/darwin_amd64/release/dapr init --slim --runtime-version=1.0.0-rc.2         
⌛  Making the jump to hyperspace...
↓  Downloading binaries and setting up components... 
Dapr runtime installed to /Users/willardstanley/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
export PATH=$PATH:/Users/willardstanley/.dapr/bin
✅  Downloaded binaries and completed components …
```

Add config file with --slim (#556)

---

cmd/dashboard.go
cmd/init.go
pkg/kubernetes/kubernetes.go
pkg/standalone/standalone.go

Signed-off-by: luhualin <luhualin@bilibili.com>
Support assign specified dashboard version for `dapr init`, such as `dapr init --runtime-version=1.0.0-rc.1 --dashboard-version=0.4.0`, so that uses can skip replace `version: latest` which may lead `403 rate limit exceeded` while calling `api.github.com`
Fix https://github.com/dapr/cli/issues/415

support assign specified dashboard version for init

---

pkg/kubernetes/upgrade.go

Fixes https://github.com/dapr/cli/issues/622
I've tested this works for the following scenarios:
1. CLI init --> CLI upgrade
2. Helm install --> CLI upgrade
3. CLI init --> Helm upgrade (and manual CRD change, as Helm doesn't update CRDs)
This PR removes the deletion of the CRDs which make the owner references kick in and delete all the associated instances.
In addition, I've verified that the upgrade path described in [this](https://github.com/dapr/cli/issues/601) issue also works.
My hypothesis is that the failure described in #601 happened because of CRDs pre 1.0.0-rc.x being registered in the system, as installing rc-1.0.0-rc.3 wouldn't have updated the CRDs at that time.

Fix crd deletions on upgrades

---

cmd/dapr.go
pkg/kubernetes/kubernetes.go
pkg/print/print.go
pkg/standalone/standalone.go

This PR:
* Adds JSON logging that emits `time`, `status`, and `msg`
* Encapsulates all testing for `runtime.GOOS == "windows"`, JSON formatting, and usage of the `spinner` package underneath the `print` package.
I will be creating a PR in `dapr/docs` to highlight this feature.
Resolves #515 
Resolves #308

Adding JSON logging format and simplifying/centralizing spinner output

---

pkg/kubernetes/status.go
pkg/kubernetes/status_test.go

dapr init -k --enable-ha=true  ## use high avaliable method to install dapr
```shell
kubectl delete pvc raft-log-dapr-placement-server-0 -n dapr-system
kubectl delete pvc raft-log-dapr-placement-server-1 -n dapr-system
kubectl delete pvc raft-log-dapr-placement-server-2 -n dapr-system
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: raft-log-dapr-placement-server-0
annotations:
volume.beta.kubernetes.io/storage-provisioner: cloud.tencent.com/xxx
finalizers:
- kubernetes.io/pvc-protection
labels:
app: dapr-placement-server
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 10Gi
storageClassName: cbs
volumeMode: Filesystem
-----------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: …
```

fix(kubernetes/status): pod not ready state will cause panic

---

README.md
cmd/init.go
cmd/uninstall.go
cmd/upgrade.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/uninstall.go
pkg/kubernetes/upgrade.go

This PR adds:
* The `--wait` and `--timeout` flags to `dapr init`
* The `--timeout` flag to `dapr upgrade` and `dapr uninstall` (These two commands already wait so the desired behavior described in the issue #597 is already implemented).
This will be tested in an upcoming PR that will add e2e tests per #412.
Resolves #597

Add --wait amd --timeout flags for dapr init -k which are passed to Helm

---

cmd/run.go
cmd/shutdown.go
cmd/shutdown_windows.go
go.mod
pkg/standalone/stop_windows.go

Windows doesn't have an easy SIGTERM equivalent, so we use a named event to signal Windows to stop Dapr gracefully.
Please reference the issue this PR will close: #631 
Without this change (run `dapr stop --app-id` in another terminal):
```bash
You're up and running! Both Dapr and your app logs will appear here.
C:\Users\Charlie\quickstarts\hello-world>echo %ERRORLEVEL%
1
```
With this change (run `dapr stop --app-id` in another terminal):
```bash
You're up and running! Both Dapr and your app logs will appear here.
terminated signal received: shutting down
Exited Dapr successfully
Exited App successfully
C:\Users\Charlie\quickstarts\hello-world>echo …
```

Use a named event for dapr stop on Windows (#631)

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go
tests/e2e/standalone/standalone_test.go

Added version field to pubsub.yaml and statestore.yaml
`dapr init` was not adding version to component specs generated, which is now required.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2964
closes #644 

Added version to component spec

---

tests/e2e/kubernetes/kubernetes_test.go

Add k8s ha mode, non-ha mode, status e2e tests, checked for pod deletion on uninstall -- used for status check failure testing.
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/660

Add k8s ha mode, non-ha mode, status e2e tests

---

.github/workflows/dapr_cli.yaml
.github/workflows/self_hosted_e2e.yaml
docs/development/development.md
go.mod

Upgrading to Go 1.16 and golangci-lint 1.39 in `go.mod` and GitHub workflow
Resolves #666 😈

Upgrading to Go 1.16 and golangci-lint 1.39

---

install/install.sh

On the MacBook Pro with Apple Silicon (M1), `uname` returns `darwin`. However, the script (line 37) only looked for `linux`, resulting in the install not running with `sudo`. The fix includes checking for `darwin` so the script will have the proper permission to write in `/usr/local/bin`.
Please reference the issue this PR will close: #634

Fix Apple Silicon (M1) install.

---

cmd/run.go
tests/e2e/standalone/standalone_test.go

On a `dapr run`, if either the daprd process or the app being run exits, dapr CLI will now detect that and exit.
Please reference the issue this PR will close: #654 

CLI run should detect that either daprd or the app has exited and clean up

---

tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go

Runtime to v1.1.1 for E2E tests.

Bump e2e runtime to v1.1.1

---

cmd/invoke.go
pkg/standalone/client.go
pkg/standalone/invoke.go
pkg/standalone/invoke_test.go
tests/e2e/standalone/standalone_test.go

The `dapr invoke` command now also has a data-file option.
Please reference the issue this PR will close: #668

Add invoke --data-file option and e2e tests

---

cmd/stop.go
tests/e2e/standalone/standalone_test.go

Add some negative self-hosted e2e. On error in stop exit with error

Add some negative self-hosted e2e. On error in stop exit with error

---

cmd/run.go

Removes the extra `\n` being printed for the application output (stdout & stderr).
Resolves #616

Removing `\n` because a newline is printed by Println

---

.github/workflows/self_hosted_e2e.yaml

We're seeing an intermittent issue with the ```open Docker.app``` command on MacOS E2E tests. 
https://github.com/dapr/cli/pull/696/checks?check_run_id=2422461523#step:4:31
Going to use an absolute path here to see if that helps.

Use absolute path for docker install MacOS

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
pkg/version/version.go

Authenticating to the Github API using the `GITHUB_TOKEN` environment variable, if set.
See https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
Related to #677 - resolves for our Github Actions Workflow pipeline.

Authentication to GitHub API using GITHUB_TOKEN environment variable

---

pkg/version/version.go

A merge to master exposed a linter problem that only shows up when you run the linter not in patch mode.

Fix a linter issue that only appeared after a merge to master.

---

.github/workflows/self_hosted_e2e.yaml

An update to Docker caused our github MacOS E2E action to fail. We found a github action that fixes this failure and allows us to require a particular version of Docker.

Debug docker install on mac

---

pkg/kubernetes/kubernetes.go

This PR applies the Dapr CRDs during the `init` process, the same as `upgrade`.

Apply CRDs on init -k

---

cmd/stop.go
tests/e2e/standalone/standalone_test.go

This changes the stop error code change done in https://github.com/dapr/cli/pull/683

Revert the changes for exit code on stop error

---

README.md
cmd/list.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/list.go
pkg/standalone/list.go
tests/e2e/standalone/standalone_test.go

Adds an `--output` to `dapr list` that allows the user to specify an alternative output format.  Valid values are `json`, `yaml`, and `table` (the default if omitted). Invalid values result in an error message.
This allows tools and other automation to more easily consume the list of running Dapr applications.
Examples:
```bash
% ./dist/darwin_amd64/release/dapr list -k         
APP ID   APP PORT  AGE  CREATED              
nodeapp  3000      18h  2021-05-25 16:22.30  
% ./dist/darwin_amd64/release/dapr list -k -o table
APP ID   APP PORT  AGE  CREATED              
nodeapp  3000      18h  2021-05-25 16:22.30  
% ./dist/darwin_amd64/release/dapr list -k -o json 
{
"appId": "nodeapp",
"appPort": "3000",
"age": "18h",
"created": "2021-05-25 16:22.30"
}%  
% ./dist/darwin_amd64/release/dapr …
```

Add `--output` option to `dapr list`

---

Makefile
cmd/buildinfo.go
pkg/standalone/version.go

Add 'build-info' command
Please reference the issue this PR will close: #599

Add 'build-info' command

---

README.md
cmd/run.go
pkg/standalone/run.go
pkg/standalone/run_test.go

Allow to specify port in placement-host-address
Please reference the issue this PR will close: #705

Allow to specify port in placement-host-address

---

install/install.ps1
install/install.sh

Adds help message with instructions when Dapr cannot installed due to lack of `sudo` or admin rights.
Please reference the issue this PR will close: #580

Add help message for installing without sudo and admin rights

---

pkg/kubernetes/kubernetes.go
pkg/version/version.go

Quick fix for #761 so that if the version is not prefixed with "v", that the major release is not trimmed.
Closes #761

Proper removal of "v" from release version

---

README.md
cmd/uninstall.go
pkg/kubernetes/uninstall.go
pkg/kubernetes/upgrade.go

This PR adds the `--all` flag to a Kubernetes uninstall command to remove all CRDs.
closes #656

Add --all flag to kubernetes uninstall

---

pkg/standalone/run.go
pkg/standalone/run_test.go

`cli` incorrectly passes boolean arguments to `daprd`.
`cli` currently uses package `flag` to parse arguments. Boolean arguments are passed as
```sh
daprd --enable-profiling true # other args follow...
```
See related code: https://github.com/dapr/cli/blob/master/pkg/standalone/run.go#L139
Actually it's not a correct way to pass boolean ones.  [Command line flag syntax](https://pkg.go.dev/flag#hdr-Command_line_flag_syntax) states that:
```text
The following forms are permitted:
-flag
-flag=x
-flag x  // non-boolean flags only
One or two minus signs may be used; they are equivalent. The last form is not permitted for boolean flags because the meaning of the command 
```
This results in a situation where our child processes inaccurately parse arguments. Please see the demo below
```go
// …
```

Run command: fix bool args passed to daprd

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml

Revert pinning of Go 1.16.6 because that is the default as of today.

Revert pinning of Go 1.16.6

---

cmd/upgrade.go

Added "downgrade" language to "upgrade" in CLI command descriptions.
Related docs PR: https://github.com/dapr/docs/pull/1703

Add downgrade language to the upgrade CLI command

---

cmd/components.go
cmd/configurations.go
cmd/dashboard.go
cmd/init.go
cmd/invoke.go
cmd/list.go
cmd/logs.go
cmd/mtls.go
cmd/publish.go
cmd/run.go
cmd/status.go
cmd/stop.go
cmd/uninstall.go
cmd/upgrade.go

Signed-off-by: Long Dai <long0dai@foxmail.com>
Log error info to stderr.
Please reference the issue this PR will close: #748

log error info to stderr

---

go.mod
go.sum
pkg/kubernetes/upgrade.go
pkg/kubernetes/upgrade_test.go

With the addition of the v2alpha1 subscription CRD, rolling back to
a previous version does not work seamlessly. This is due to k8s not
allowing a new CRD without the v2alpha1 version.
As CRDs are additive skipping their removal when downgrading should
not impact anything. Handling this with an implicit flag allows for
users to have an easy experience without touching the CRDs.
Please reference the issue this PR will close: Endgame

Skip CRD application during downgrade

---

cmd/init.go

Allows optionally specifying of the runtime version with an environment variable.
When using `dapr init` / `dapr init -k` in workflows and tests it is handy to specify the runtime version via an environment variables.
This is particularly true where Dapr's Mechanical Markdown is used and the runtime version itself should not appear in the code snippets.
E.g. Quickstart validation, sample validation for Python and Go SDKs
Full example
```bash
export DAPR_RUNTIME_VERSION=1.4.3-rc.1
dapr init
```
Output
```
⌛  Making the jump to hyperspace...
ℹ️  Dapr runtime version: 1.4.3-rc.1
ℹ️  Installing runtime version 1.4.3-rc.1
↓  Downloading binaries and setting up components...
Dapr runtime installed to /Users/bverst/.dapr/bin, you may run the following to add it to your path if you want to run …
```

Allow specifying of runtime-version via Env Var for `dapr init`

---

go.mod
go.sum
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/upgrade/upgrade_test.go

Update tests to use Dashboard 0.9.0-rc.1 and Runtime 1.5.0-rc.3
Also updates go.mod to use dapr/dapr 1.5.0-rc.3 (which doesn't actually include runtime code changes compared to 1.5.0-rc.1)

Update tests and build for runtime 1.5.0-rc.3

---

.github/workflows/dapr_cli.yaml
install/install.sh

Adds native binary support for Darwin Arm64 (e.g. M1 Mac)

Adds native binary support for Darwin Arm64 (e.g. M1 Mac)

---

.github/workflows/dapr_cli.yaml
install/install.sh

- This cherry-picks commit 78db31a6b4946262854b4f8399b77f7f0ed19260 from Release-1.5 into master.
- Fixes an issue in the install script.
The install scripts are only run from the Master branch and therefore this change needs to be cherry picked ahead of the release.
* Add Darwin ARM64 binaries
* Update install script for Darwin Arm64

Install script update for Darwin ARM 64 (M1 Mac etc) support

---

install/install.sh

Cherry picks 75fef9e2a672eba6dd8ffb85138a4b988b7602cc from master to avoid a merge conflict when we merge release back into master.

Cherry-pick: Fix install script for M1 mac

---

pkg/standalone/publish.go
pkg/standalone/publish_test.go
pkg/standalone/testutils.go
tests/e2e/standalone/standalone_test.go
tests/e2e/testdata/cloudevent.json

Publish events with CloudEvent envelope with content type `application/cloudevents+json`
Added logic to detect CloudEvent envelopes by checking for the required fields `id`, `source`, `spec version`, `type`, and `data`. If all of these attributes are present, the content type is changed from `application/json` to `application/cloudevents+json`.
Most of the change was getting the unit tests to be more flexible with the HTTP test server handler logic.
I will be creating a Docs PR to add this information to https://docs.dapr.io/reference/cli/dapr-publish/
Closes #838

Publish events with CloudEvents envelopes

---

.gitignore

Go 1.18 introduces Go workspaces. These can be used to pin specific go versions or maybe locally built library versions / dependencies.
See `https://github.com/golang/go/issues/45713`
This avoids the need to constantly update go.mod for local development. For example I commonly use replace to refer to components-contrib and dapr on my local file system instead of the remote.

Ignore go.work for Go 1.18 Workspaces

---

pkg/metadata/metadata.go
tests/e2e/standalone/standalone_test.go

Signed-off-by: Loong <loong.dai@intel.com>
Go-retryablehttp cannot close idle socket connections, need to call it by hand.
Fix https://github.com/dapr/dapr/issues/3894

fix shutdown hang when enable socket

---

pkg/metadata/metadata.go
tests/e2e/standalone/standalone_test.go

Cherry-Pick into Release 1.5 PR #835

Cherry-Pick into Release 1.5 PR #835

---

pkg/kubernetes/client.go

Kube config delimiter is semicolon on windows, which is different from colon on other platform.
Please reference the issue this PR will close: #779

feat: support windows style delimiter

---

README.md
cmd/run.go
pkg/standalone/run.go
pkg/standalone/run_test.go

- In the past, I opened this PR: https://github.com/dapr/cli/pull/770. Changes look like a mess. I close the PR and made this one.
- CLI only passes 03 env variables to applications. See [run.go#L185-L187](https://github.com/dapr/cli/blob/master/pkg/standalone/run.go#L185-L187)
- There are more.  See [Docs](https://docs.dapr.io/reference/environment/)
- Python SDK has a different view on such variables. See [global_settings.py](https://github.com/dapr/python-sdk/blob/master/dapr/conf/global_settings.py). This leads to `not-working` [tutorial](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#step-1-choose-an-id-for-your-service)

Run: pass missing env variables

---

.github/workflows/dapr-bot-schedule.yml

Signed-off-by: Long Dai <long0dai@foxmail.com>
Add stale bot to control issue/pr lifecycle.
It is safe to merge before label, since it would mark those as stale and wait for 37 days to close.

ci: add stale bot

---

install/install.sh

Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>
Currently the installer corrupts binaries when the Dapr version is updated. This addresses the problem.

Installer: Remove old Dapr CLI to avoid file corruption

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml
docs/development/development.md
go.mod

Upgrade to Go 1.17 in `go.mod` and update docs/workflows. Additionally, run `go mod tidy --go=1.17`.
Please reference the issue this PR will close: #802 

Upgrade to Go 1.17

---

pkg/standalone/standalone.go

Enable Redis Query to work in self-hosted developer deployments with Dapr init
Please reference the issue this PR will close: #906

dapr init: enable redis query to work in self-hosted environment

---

README.md
cmd/mtls.go
cmd/renew_certificate.go
cmd/upgrade.go
pkg/kubernetes/common.go
pkg/kubernetes/renew_certificate.go
pkg/kubernetes/upgrade.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/testdata/namespace.yaml
tests/e2e/testdata/statestore.yaml

Adding new commands to renew expiring certificate.
```
dapr mtls renew-certificate -k --valid-until <no of days> --restart
dapr mtls renew-certificate -k --certificate-password-file myprivatekey.key --valid-until <no of days>
dapr mtls renew-certificate -k --ca-root-certificate <ca.crt> --issuer-private-key <issuer.key> --issuer-public-certificate <issuer.crt> --restart
```
Please reference the issue this PR will close: #892 

Changes for cli command to renew certificate

---

pkg/standalone/standalone.go

This reverts commit f3cecee471ca53e728bb56f59bd74dd26da50915.
Reference -  PR discussion on https://github.com/dapr/cli/pull/930.  rejson has support for amd64 arch only, whereas redis has support for many archs.
https://hub.docker.com/r/redislabs/rejson/tags
https://hub.docker.com/_/redis/?tab=tags

Revert "dapr init: enable redis query to work in self-hosted env

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

Added a check to not retry pull and not print unnecessary log when image-registry flag is provided
Please reference the issue this PR will close: #939 

Fix for image pull from private registry

---

cmd/renew_certificate.go
pkg/kubernetes/mtls.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go

Made changes, so that to flags present in below commands cannot be mixed.
a. `dapr mtls renew-certificate -k --ca-root-certificate <ca.crt> --issuer-private-key <issuer.key> --issuer-public-certificate <issuer.crt>`
b. `dapr mtls renew-certificate -k --private-key myprivatekey.key`
if any one of the flags is provided in 1st command, it will still try to execute the flow assuming all 3 are provided and will throw error if not all params are provided.
Please reference the issue this PR will close: #941 

Do not allow mixing of flags in renew cert

---

cmd/init.go
pkg/standalone/bundle.go
pkg/standalone/bundle_test.go
pkg/standalone/docker.go
pkg/standalone/standalone.go
pkg/standalone/standalone_test.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/standalone_test.go

Fix `--from-dir` init flow. 
Based on the PR https://github.com/dapr/installer-bundle/pull/3, this PR changes init flow when `--from-dir` flag is specified to expect a `details.json` file.
It will parse the `details.json` file to know the image that was saved as well as the file name it was saved as. 
Also as previous flow, the runtime and dashboard versions are determined from the `details.json` file as well.
isAirGapInit just encapsulates the value of bool comparing fromDir length to zero. isAirGapInit seems a more expressive way of checking for a particular condition in a flow.
Added more comments on the current init flow. 
Create a separate `bundle.go` which basically just parses the `details.json` file and added a unit test for the same. 
When both `--from-dir` and `--image-registry` …

Change `--from-dir` init flow

---

.github/workflows/dapr_cli.yaml

We currently use golangci/golangci-lint-action's v2.2.1 which installs the latest go version (1.18 in this case). Upgrade to v3.1.0 which reuses the pipeline's go installation.
Related to https://github.com/dapr/components-contrib/issues/1639

Update golangci-lint-action to v3.1.0

---

pkg/kubernetes/uninstall.go
pkg/kubernetes/upgrade.go

Fixes https://github.com/dapr/cli/issues/975.
This PR does several things:
1. Fixes issue #975 by adding the resiliency CRD to the list of CRDs to be applied to the cluster and removed when uninstalled
2. Fixes an issue where a user tries to install a version of Dapr (for example, 1.1.0) with a CLI that tries to apply CRDs that are not available in the desired version (for example, trying to install Dapr 1.1.0 with CLI 1.5.0 will fail because the CLI can't find the subscription CRD for 1.1.0). This is done by checking if the CRD exists for the required version before attempting to apply it to the cluster.
3. Fixes an issue where users trying to uninstall an older version of Dapr with a newer CLI is failing because the older version doesn't have a CRD that the CLI is trying to uninstall. …

Fix CRD handling for upgrades and removals

---

.github/workflows/self_hosted_e2e.yaml

Switching to `brew install` instead of using `actions-setup-docker` github action, as with the action docker setup seems highly unstable. This way it might increase the time to setup docker on macos (can take upto 10 mins) but atleast it looks more stable. It failed once in last 4 runs. See here- https://github.com/pravinpushkar/cli/actions/workflows/self_hosted_e2e.yaml
Related discussions can be found here - https://github.com/docker/for-mac/issues/2359
Please reference the issue this PR will close: #981 

Script for docker install instead of actions-setup-docker

---

pkg/kubernetes/upgrade.go

Handle panic caused while trying to upgrade an edge version of Dapr.
Please reference the issue this PR will close: #954 

Fix for panic during upgrade of edge version dapr

---

pkg/standalone/standalone.go

Fixes airgap init in standalone mode, where some unnecessary config/component files were being created, causing dapr run to fail afterwards.
Please reference the issue this PR will close: #970 

Fixing airgap init

---

cmd/dapr.go
cmd/version.go

Add newline char at end of dapr version cmd output
Please reference the issue this PR will close: #1013 

Add newline char at end of dapr version output

---

README.md
cmd/annotate.go

Signed-off-by: Joni Collinge <jonathancollinge@live.com>
Require the -k flag to target Kubernetes for the `dapr annotate` command to make it consistent with other commands.
* [xx] Extended the documentation

Require -k flag for annotate command

---

.golangci.yml
cmd/annotate.go
cmd/invoke.go
cmd/publish.go
pkg/kubernetes/annotator_test.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/mtls.go
pkg/kubernetes/portforward.go
pkg/kubernetes/renew_certificate.go
pkg/metadata/metadata.go
pkg/standalone/bundle.go
pkg/standalone/invoke.go
pkg/standalone/run.go
pkg/standalone/standalone.go
pkg/standalone/standalone_test.go
pkg/version/version.go
tests/e2e/standalone/standalone_test.go
utils/utils.go

The current minimum version of dapr is golang 1.18, which is no longer compatible with the previous version and can remove the marked deprecated functions.

Removing the use of the ioutil package

---

cmd/init.go
cmd/uninstall.go
tests/e2e/standalone/commands.go
tests/e2e/standalone/init_test.go
tests/e2e/standalone/uninstall_test.go
tests/e2e/standalone/utils.go
utils/utils.go
utils/utils_test.go

This PR limits the container runtime configuration to `docker` and `podman` only. 
Please reference the issue this PR will close: #1098

Validate and limit container runtime configuration in init and uninstall commands

---

pkg/kubernetes/kubernetes.go

Signed-off-by: shivam <shivamkm07@gmail.com>
`dapr init -k` installs "latest" dapr runtime instead of the latest version (1.9.0 currently). The PR fixes it to pick up the correct version
Please reference the issue this PR will close: #1104 

fix kubernetes init to pick correct runtime version

---

.github/workflows/self_hosted_e2e.yaml

Remove dependency from Helm since it's no longer available in the latest macOS.
Uses bash magic to get version for both dashboard and runtime from GitHub releases.
Please reference the issue this PR will close: #1130 

Remove helm dependency from e2e test suite

---

cmd/run.go
pkg/standalone/run.go
pkg/standalone/run_test.go

When we use vpn, the ip becomes complicated, support custom listen address helps us to solve this problem
https://github.com/dapr/dapr/pull/3429

Support -dapr-listen-address option to daprd

---

.github/workflows/self_hosted_e2e.yaml

Use the GH authentication token to prevent getting throttled. The limit for authenticated requests is 15000 per hour (as opposed to 60 per hour for unauthenticated). Note, if it still does not work, it falls back to the default versions.
Please reference the issue this PR will close: #1133

Authenticate requests to GH API to prevent getting throttled

---

.github/workflows/kind_e2e.yaml

Similar to standalone e2e, use the GH API in KinD e2e tests instead of helm.
Please reference the issue this PR will close: #1130

Update KinD e2e tests to use GH API instead of helm for fetching latest releases

---

README.md
cmd/renew_certificate.go
pkg/kubernetes/renew_certificate.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
utils/utils.go
utils/utils_test.go

In case, where control plane has mariner variant images, the renew-cert will fail while getting the helm chart for current version(1.9.0-mariner) in this case. 
Here, the version is read from `Status` command which appends `mariner` to the actual version. So, we need extract the version from complete tag.
Please reference the issue this PR will close: #1125 

mariner renew-certificate fix

---

.github/workflows/self_hosted_e2e.yaml
Makefile

Increase the timeout from 10m to 15m for self-hosted e2e tests. This was causing failures in #1057. This PR has been tested on top of changes from #1057 in #1156

Increase timeout for self hosted e2e tests on MacOS runner

---

.github/workflows/self_hosted_e2e.yaml
Makefile

Earlier e2e test timeout was only applicable for GHCR cron runs, now it's also extended to Dockerhub.
The Makefile is also updated to always use a default value if the environment variable is unset.
NA

Add e2e timeout to Dockerhub runs and update Makefile default

---

cmd/version.go

Other sub command help text don't end in a full stop. 
Before:
```
__
____/ /___ _____  _____
/ __  / __ '/ __ \/ ___/
/ /_/ / /_/ / /_/ / /
\__,_/\__,_/ .___/_/
/_/
===============================
Distributed Application Runtime
Usage:
dapr [command]
Available Commands:
annotate       Add dapr annotations to a Kubernetes configuration. Supported platforms: Kubernetes
build-info     Print build info of Dapr CLI and runtime
completion     Generates shell completion scripts
components     List all Dapr components. Supported platforms: Kubernetes
configurations List all Dapr configurations. Supported platforms: Kubernetes
dashboard      Start Dapr dashboard. Supported platforms: Kubernetes and self-hosted
help           Help about any command
init           Install Dapr on supported hosting …
```

nit: Remove full stop from version string to match other subcommand help output

---

pkg/standalone/run.go
pkg/standalone/run_test.go

Setting defaults values in the struct tag along with the run flags.

set default fields via struct default tag

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

Use FQDN when Dockerhub is set as the default regirstry.
Please reference the issue this PR will close: #1090 

use fqdn for all image names when dockerhub is the registry

---

cmd/buildinfo.go
cmd/dapr.go
cmd/dashboard.go
cmd/init.go
cmd/run.go
cmd/uninstall.go
pkg/runexec/runexec_test.go
pkg/standalone/common.go
pkg/standalone/common_test.go
pkg/standalone/run.go
pkg/standalone/runfileconfig/run_file_config_parser.go
pkg/standalone/runfileconfig/run_file_config_parser_test.go
pkg/standalone/standalone.go
pkg/standalone/uninstall.go
tests/e2e/standalone/init_run_custom_path_test.go
tests/e2e/standalone/init_test.go
tests/e2e/standalone/run_test.go
tests/e2e/standalone/version_test.go

Fix custom path installation logic.
Always install inside `.dapr` folder in the given input folder.
Added UTs for the same.
On uninstall only uninstall `.dapr` folder from the given input folder.
Custom path installation logic is `init check, version check, run command check, uninstall check` in order for 3 scenarios.
- `--runtime-path` flag is given 
- `DAPR_RUNTIME_PATH` env var is given
- Both flag and env var are given
Modified E2E. 
Fixed Version flag to work with `--runtime-path` flag and also version command to work with `--runtime-path` flag.
Modified Version E2E to check right output of version (edge for CLI and pinned version for runtime).
Added version command E2E for `--runtime-path`(as stated above).
related to https://github.com/dapr/cli/issues/1056
We strive to have all PR …

Fix runtime custom path installation logic

---

tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/standalone/init_test.go

Signed-off-by: Shivam Kumar <shivamkm07@gmail.com>
This PR adds the test for init with mariner images without using --runtime-version flag. 

Adding more e2e tests for mariner images

---

pkg/standalone/list.go
tests/e2e/standalone/list_test.go

In previous version dapr run puts the `--enable-app-health-check` at the end of the args list, while 1.10 put it in the middle. Below is an example of the command dapr starts daprd.
```
/root/.dapr/bin/daprd --app-id Watcherswift-Carp --app-port 3000 --dapr-http-port 41309 --dapr-grpc-port 39479 --config /root/.dapr/config.yaml --app-protocol http --profile-port -1 --log-level info --app-max-concurrency -1 --placement-host-address localhost:50005 --components-path /root/.dapr/components --metrics-port 33949 --dapr-http-max-request-size -1 --dapr-http-read-buffer-size -1 --dapr-internal-grpc-port 44463 --enable-app-health-check
#now
/root/.dapr/bin/daprd --config /root/.dapr/config.yaml --app-protocol http --log-level info --app-max-concurrency -1 --placement-host-address localhost:50005 …
```

Fix unexpected behaviour in dapr list

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

Init logging now logs using container runtime specified by the user, instead of always logging "Docker".
Please reference the issue this PR will close: #1209

Show correct container runtime in init logging

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml
Makefile
docs/development/development.md
go.mod
pkg/standalone/uninstall.go
tests/apps/emit-metrics/go.mod
tests/apps/processor/go.mod

For #1243 
To upgrade go version to 1.20.
Please reference the issue this PR will close: #1243 

Upgrade go version to 1.20

---

cmd/dapr.go

Fixed the problem that the output of the dapr did not match the documentation after installation.
Please reference the issue this PR will close: #1254

output help information when dapr has no parameters

---

.github/workflows/dapr_cli.yaml

Instead of github-release-cli, use official GH cli to publish artifacts to github.
closes #1230
Please reference the issue this PR will close: #1230

Use offical GH CLI instead of npm github-release-cli

---

pkg/kubernetes/upgrade.go

Add `httpendpoints` for cli build so operator doesn't go into crash loop backoff with 1.11 RC CLI update PR here https://github.com/dapr/cli/pull/1284
https://github.com/dapr/cli/pull/1280
needed for https://github.com/dapr/cli/pull/1284

fix(build): add httpendpoint resource

---

cmd/run.go
pkg/runexec/runexec_test.go
pkg/standalone/run.go
tests/e2e/standalone/invoke_test.go
utils/utils.go

add app channel address flag for run

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go
pkg/standalone/uninstall.go
utils/utils.go

The previous logic to check if a container runtime is installed or not, used an OR logic. This resulted in issues like #1300
```go
containerRuntimeAvailable := utils.IsDockerInstalled() || utils.IsPodmanInstalled() 
```
The new fix is to check for a specific runtime based on the flag passed by the user.
Please reference the issue this PR will close: #1300

Fix checks for container runtime installation

---

pkg/standalone/standalone.go
utils/utils.go
utils/utils_test.go

dapr init fails to run with certain username on Windows.
This issue was caused because of an extra apostrophe or single quote in the username since powershell considers it as special character and hence creates syntax issues. To solve this, I created a function in '/utils/utils.go' to take any command and converts into powershell compatible command by appending another quote character after every such character. This makes the command powershell compatible. Now it doesn't throw any syntax error and runs as expected.
Closes #972 
PS C:\Users\Carlin'tVeld> cd D:
PS D:\> .\dapr.exe init
Making the jump to hyperspace...
Container images will be pulled from Docker Hub
Installing runtime version 1.11.1
Downloading binaries and setting up components...
Downloaded binaries and completed …

Fix for Quote in username errors dapr init #972

---

pkg/standalone/run.go
pkg/standalone/run_test.go

This PR is the companion of https://github.com/dapr/dapr/pull/6512 which makes the same change in the Dapr Injector.
It adds the `APP_PROTOCOL` env var for the app that is being started with `dapr run`. As explained in the PR in dapr/dapr, this is helpful for the app to know if it should start a server with HTTPS or H2C enabled.

Add APP_PROTOCOL env var for app

---

pkg/standalone/standalone.go

Expose `healthz` and `metrics` ports when running self-hosted with docker.
Map `healthz` to 58080, and `metrics` to 59090, to keep 5xxxx port pattern and keep 8080 and 9090 port numbers which are easier to remember what these ports are mapped to.
Please reference the issue this PR will close: #800 

Add health and metrics port mapping for placement stand-alone mode

---

.github/workflows/self_hosted_e2e.yaml

fail-fast set to false until macos tests are fixed.

Self Hosted E2E - fail-fast set to false

---

cmd/run.go
cmd/stop.go
go.mod
go.sum
pkg/standalone/stop_windows.go
pkg/syscall/syscall.go
pkg/syscall/syscall_windows.go
tests/e2e/standalone/run_template_test.go
tests/e2e/standalone/stop_with_run_template_test.go
tests/e2e/standalone/windows_run_template_test.go
tests/e2e/testdata/run-template-files/app_output_to_only_console.yaml
utils/utils.go

- Support Multi app run on windows
- Support `dapr stop -f <run_template_path>` 
Please reference the issue this PR will close: 
#1220 
#1221 

Multiapp run and stop implementation for windows

---

.github/workflows/dapr_cli.yaml
.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
.github/workflows/upgrade_e2e.yaml
.golangci.yml
cmd/dashboard.go
pkg/kubernetes/annotator.go
pkg/kubernetes/annotator_test.go
pkg/standalone/invoke.go
pkg/standalone/publish.go
pkg/standalone/stop.go
tests/e2e/upgrade/upgrade_test.go

Fixed upload artifacts version.
fix upload artifact name conflict with the migration guide https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

fix upload artifact name conflict

---

README.md
pkg/kubernetes/upgrade.go

There's a flake in the upgrade test from 1.11.0 to 1.12.0, this is a version where we upgrade the `configuration` CRD by adding two new fields:`controlPlaneTrustDomain` and `sentryAddress`.
The flake stems from a known race condition that arises when both updating a CRD and a matching CR close together (described [here](https://github.com/kubernetes/kubectl/issues/1179)). This patch introduces a basic retry mechanism, it needs a fresh client on each try to the OpenAPI schema caching that's happening in the [kubectl client](https://github.com/kubernetes/kubectl/blob/master/pkg/util/openapi/openapi_getter.go#L48).
No issue referenced so far but a few occurrences of the flake can be seen in the [GHA history](https://github.com/dapr/cli/actions?query=is%3Afailure)
The error is typically …

Fix flaky upgrade test

---

pkg/standalone/standalone.go

Updated default directory permissions to 755 for components and bin directories.
Please reference the issue this PR will close: #1317 

Fix default installation directory permissions

---

pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

Fix check for version to contain scheduler.
Please reference the issue this PR will close: #1416

Fix check for version to contain scheduler.

---

cmd/annotate.go
cmd/run.go
go.mod
pkg/kubernetes/renew_certificate.go
pkg/kubernetes/uninstall.go
pkg/standalone/run.go
pkg/standalone/standalone.go
tests/e2e/common/common.go
tests/e2e/standalone/windows_run_template_test.go

Refactors the way `scheduler-host-address` is handled and adds the arg to enable standalone mode runs.
The scheduler can now be initialised by flag with the run command, if an older runtime is installed there is some janky logic to not pass the flag. Instead, a notice is displayed.
Please reference the issue this PR will close: #1420 

fix: scheduler host address passed to runtime

---

cmd/init.go
pkg/standalone/common.go
pkg/standalone/standalone.go
pkg/standalone/standalone_test.go

Expose `--scheduler-volume` to optionally specify the volume which scheduler writes to.

dapr_scheduler: Adds scheduler-volume flag

---

Makefile
cmd/init.go
cmd/uninstall.go
pkg/standalone/uninstall.go

Give scheduler a default volume, making it resilient to restarts by

---

pkg/standalone/standalone.go
tests/e2e/standalone/init_test.go

Fix dapr init scheduler

---

pkg/standalone/standalone.go

Changes scheduler data dir in selfhosted mode to be under `/var/lib/dapr/scheduler` as this is strictly more correct under FSH.
https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#varlibVariableStateInformation

Change scheduler container data dir from `/var/run/...` to `/var/lib/...`

---

pkg/standalone/standalone.go

Fix the permission denied issue with scheduler data-dir. 
Big thanks from a pairing session w/ @JoshVanL & @antontroshin 🎉

Fix Scheduler Data Dir Permissions Issue

---

pkg/kubernetes/status.go
pkg/kubernetes/status_test.go

Fix `dapr status -k` showing `dapr-scheduler-server` pods information
Please reference the issue this PR will close: #1433 

Add dapr scheduler server to the status command

---

pkg/kubernetes/kubernetes.go

Pins the bitnami version to a stable one and removes unneeded Redis replicas for dev mode.
Fixes #1436 
and https://github.com/dapr/quickstarts/issues/1048

Pin bitnami chart version for redis

---

pkg/standalone/run.go

Remove Docker client dependency from standalone run

---

.github/workflows/kind_e2e.yaml
.github/workflows/self_hosted_e2e.yaml
pkg/standalone/standalone.go
tests/e2e/standalone/commands.go
tests/e2e/standalone/init_negative_test.go
tests/e2e/standalone/init_run_custom_path_test.go
tests/e2e/standalone/init_test.go
tests/e2e/standalone/invoke_test.go
tests/e2e/standalone/list_test.go
tests/e2e/standalone/publish_test.go
tests/e2e/standalone/run_template_test.go
tests/e2e/standalone/run_test.go
tests/e2e/standalone/stop_test.go
tests/e2e/standalone/stop_with_run_template_test.go
tests/e2e/standalone/uninstall_test.go
tests/e2e/standalone/utils.go
tests/e2e/standalone/version_test.go
tests/e2e/standalone/windows_run_template_test.go

Fix standalone e2e tests
Fix podman e2e install
Fix scheduler start failure on the standalone mariner image variant

Fixing e2e tests, podman and scheduler fail with mariner images

---

pkg/version/version.go
pkg/version/version_test.go

Fix a panic when an incorrect version is pulled from dapr releases page.
For example, this happened when a new release tag `vedge` was introduced.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1961f53]
goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0)
/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:369 +0x33
github.com/hashicorp/go-version.(*Version).Compare(0x0, 0xc00077c000)
/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:116 +0x25
github.com/hashicorp/go-version.(*Version).GreaterThan(...)
/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:298 …
```

Add version parsing check skip malformed versions and avoid panic

---

cmd/run.go

Allows the scheduler to run for "edge" builds without a runtime version

fix: allow the scheduler client to initialise for edge builds

---

pkg/standalone/list.go

The CLI currently uses a deprecated flag in `daprd` for max request size and read buffer body. This PR sets the correct flags. The CLI can continue to exist with the user facing `--dapr` prefix.

Use non-deprecated flags in List operation

---

pkg/standalone/standalone.go

Requires https://github.com/dapr/dapr/pull/8416 & v1.15.0-rc.6

Scheduler: set broadcast address to localhost:50006 in selfhosted

---

pkg/standalone/standalone.go

Fix the scheduler standalone broadcast address on Windows.
Docker forwarded ports are different for the scheduler and placement

Fix scheduler broadcast address for windows

---

pkg/kubernetes/configuration.go

The issue found when similar resource were installed in k8s that use the name "configurations". In this case the knative's "configurations.serving.knative.dev/v1" was the last in the list and the command returned the error `Error from server (NotFound): configurations.serving.knative.dev "daprsystem" not found`
Please reference the issue this PR will close: #1485 

Fix daprsystem configuration retrieval when renewing certificates

---

cmd/annotate.go
cmd/run.go
pkg/runexec/runexec_test.go
pkg/standalone/run.go

`max-body-size` and `read-buffer-size` now accept units as defined in the docs.
Defaults of 4Mi and 4Ki respectively are also set
Fixes #1489

fix: arguments accept units

---

pkg/kubernetes/upgrade.go
pkg/kubernetes/upgrade_test.go
tests/e2e/common/common.go

The issue is that the scheduler by default uses 3 replicas, which incorrectly identified non-HA install as HA.
This fix should allow for PR https://github.com/dapr/cli/pull/1491 to progress with testing newer version upgrade/downgrade

Fix dapr upgrade command incorrectly detecting HA mode for new version 1.15

---

cmd/run.go

`dapr run -f` command was not adjusting scheduler address on Windows, same as it does when using `dapr run -- ` plain command.
Please reference the issue this PR will close: #1496

Fix scheduler address for dapr run with file on Windows

---

.github/workflows/kind_e2e.yaml
.github/workflows/upgrade_e2e.yaml
Makefile
pkg/kubernetes/upgrade.go
tests/e2e/common/common.go
tests/e2e/kubernetes/kubernetes_test.go
tests/e2e/kubernetes/run_template_test.go
tests/e2e/upgrade/upgrade_test.go

Upgrade/downgrade tests for these pairs:
- 1.13.6 -> 1.14.4
- 1.13.6 -> 1.15.0-rc.16
- 1.14.4 -> 1.15.0-rc.16
- 1.14.4 -> 1.15.0-rc.16 (mariner)
- 1.15.0-rc.16 -> 1.14.4
- 1.15.0-rc.16 -> 1.13.6
- 1.14.4 -> 1.13.6

release: test upgrade/downgrade for 1.13/1.14/1.15 + mariner

---

pkg/standalone/stop_windows.go
pkg/syscall/syscall_windows.go
tests/e2e/standalone/init_test.go

Some `dapr init` tests use the actual latest release from GitHub when running `dapr init` without `--runtime-version` flag. This breaks when a new version is released.
Changed the tests to compare the latest version from GitHub instead of env variable.
Lint fixes.

Fix dapr init test latest version retrieval

---

cmd/run.go
cmd/run_test.go
go.mod

This PR adds detection for incompatible flags when using the `--run-file` flag in the `dapr run` command. When a user tries to use command line flags that are incompatible with the run file configuration, a warning message is now displayed to inform the user that these flags will be ignored and should instead be configured in the run file.
Please reference the issue this PR will close: #1508 
- Added a list of flag names that are incompatible with the `--run-file` option
- Implemented a detection function (`detectIncompatibleFlags`) that identifies when incompatible flags are being used
- Created a message generator (`generateWarningMessage`) to create a clear warning for users
- Added logic in the run command to check for incompatible flags and display warnings
- Added unit tests for …

Add detection for incompatible flags with --run-file

---

cmd/run.go
pkg/standalone/run.go
pkg/standalone/run_test.go

- This PR fixes a behavior where passing an explicitly empty placement host address should disable Placement, but instead the runtime still attempted to connect. It also aligns the CLI behavior and help so that users can reliably disable Placement without actors/workflows.
Please reference the issue this PR will close: fixes: https://github.com/dapr/dapr/issues/9000

fix: allow explicit disable of placement with empty host (v1.16)
